### ISSUE TITLE
running nanocorr in a non-SGE context

### ISSUE THREAD

**Issue by ragak** [jgurtowski/nanocorr#12]
Hi, I just wanted to suggest a few small corrections to the code for running nanocorr outside the context of a SGE. I had to fiddle with it a bit to get it to work:

Note: replace ## with the number of files in your partitioned folder

for j in {1..##}; do 
    export SGE_TASK_ID=$j
    export TMPDIR='/tmp'
    python /path_to_nanocorr/nanocorr.py /path_to_data/data.fasta /path_to_ref/PCRpass_2D.fasta
done

Seems to be working for me, but let me know if there's an issue with it.
Thank you!

**Comment by jgurtowski** [comment]
Ok, I'm glad it works for you now.
