### ISSUE TITLE
BLAST

### ISSUE THREAD

**Issue by noahsundberg** [jgurtowski/nanocorr#13]
Can anyone please clarify what "Blast to be in path" means. I have put a yeast database from the ncbi website and it still gives me an error that looks like this:
 Error: NCBI C++ Exception:
    T0 "/home/coremake/release_build/build/PrepareRelease_Linux64-Centos_JSID_01_80348_130.14.18.6_9008__PrepareRelease_Linux64-Centos_1433254587/rpmbuild/BUILD/ncbi-blast-2.2.31+/c++/src/objtools/readers/fasta.cpp", line 2203: Error: ncbi::objects::CFastaReader::PostWarning() - CFastaReader: Near line 1, there's a line that doesn't look like plausible data, but it's not marked as defline or comment. (m_Pos = 1)

BLAST Database error: No alias or index file found for nucleotide database [/home/selmecki/patrick_minion/0001/W303_ONT_Raw_reads.fa] in search path [/home/selmecki/patrick_minion/0001/tmp::]
Failed : blastn -db /home/selmecki/patrick_minion/0001/W303_ONT_Raw_reads.fa -query p0014.blast6.r.fa -outfmt "6 std qlen slen" -evalue 1e-10 -reward 5 -penalty -4 -gapopen 8 -gapextend 6 -dust no -task blastn -out p0014.blast6.r.refblast6

I have BLAST saved in the /0001 directory, which is where the program is being run.

**Comment by noahsundberg** [comment]
Here's a screen shot if it helps any:
![nanocorr_error](https://cloud.githubusercontent.com/assets/20971810/17591877/aa57b6aa-5fa5-11e6-8a70-06b8538d21a7.jpg)

**Comment by jgurtowski** [comment]
Try running this first:

$>makeblastdb -dbtype nucl -in /home/selmecki/patrick_minion/
0001/W303_ONT_Raw_reads.fa

**Comment by noahsundberg** [comment]
Thank you, that resolved the issue.
