### ISSUE TITLE
sh: blast6Filter: command not found

### ISSUE THREAD

**Issue by MattHodgman** [jgurtowski/nanocorr#20]
I get the following error when running nanocorr.py. I cannot find anything that talks about blast6Filter.... what do I do?

I am using slurm instead of SGE.

Here is the nanocorr.py output:

Building a new DB, current time: 02/03/2020 20:55:48
New DB name:   /lustre/scratch/usr/matthodg/assemblyMethods/n1_partitions/tmp/p0001
New DB title:  p0001
Sequence type: Nucleotide
Deleted existing Nucleotide BLAST database named /lustre/scratch/usr/matthodg/assemblyMethods/n1_partitions/tmp/p0001
Keep MBits: T
Maximum file size: 1000000000B
Adding sequences from FASTA; added 100 sequences in 0.142373 seconds.

sh: blast6Filter: command not found
Running : cp /lustre/scratch/usr/matthodg/assemblyMethods/n1_partitions/0001/p0001 .
Running : makeblastdb -dbtype nucl -in p0001
Running : blastn -db p0001 -query /fslhome/matthodg/compute/assemblyMethods/n1_partitions/0001/p0001 -outfmt "6 std qlen slen qseq sseq" -dust no -task blastn -reward 5 -penalty -4 -gapopen 8 -gapextend 6 -evalue 1e-15 | sort -k 2,2 -k 9,9n > p0001.blast6
Running : cp p0001.blast6 /lustre/scratch/usr/matthodg/assemblyMethods/n1_partitions/0001
Running : blast6Filter r_experimental p0001.blast6 > p0001.blast6.r
Failed : blast6Filter r_experimental p0001.blast6 > p0001.blast6.r

This is the bash script (w/o resource requests) that I use to run nanocorr.py:

dir="$1"
source /fslhome/matthodg/compute/assemblyMethods/nanocorr/nanocorr_ve/bin/activate
export PATH=$PATH:/fslhome/matthodg/compute/assemblyMethods/ncbi-blast-2.10.0+/bin/
module load python
fileNumber="$(printf "%04d\n" $SLURM_ARRAY_TASK_ID)"
echo ${dir}/p${fileNumber}
env SGE_TASK_ID=$SLURM_ARRAY_TASK_ID TMPDIR=/fslhome/matthodg/compute/assemblyMethods/n1_partitions/tmp python /fslhome/matthodg/compute/assemblyMethods/nanocorr/nanocorr.py /fslhome/matthodg/compute/assemblyMethods/n1_partitions/${dir}/p${fileNumber}

**Comment by jgurtowski** [comment]
blast6Filter is installed by the jgurtowski/jptools package. Is that package installed (via the README) into your virtual environment and is it in your PATH?

**Comment by MattHodgman** [comment]
It was an error with that. Thank you!
