### ISSUE TITLE
pbdagcon installation

### ISSUE THREAD

**Issue by schellt** [jgurtowski/nanocorr#21]
Dear James,
while installing nanocorr, I encountered errors after executing
`pip install git+https://github.com/jgurtowski/pbdagcon_python`
See the attached files for details.
Do you have an idea how to fix this?
Thanks a lot.
Best regards,
Tilman

[pip_install_pbdagcon-log.txt](https://github.com/jgurtowski/nanocorr/files/4627449/pip_install_pbdagcon-log.txt)
[pip_install_pbdagcon-err.txt](https://github.com/jgurtowski/nanocorr/files/4627450/pip_install_pbdagcon-err.txt)

**Comment by jzohren** [comment]
Hi James and Tilman,

I'm having the same issue while trying to install the pbdagcon library. Did either of you manage to solve this?

Thanks and best wishes,
Jasmin

**Comment by jgurtowski** [comment]
Sorry the installation is not working. This package is no longer being maintained. Please try an alternative such as Canu https://github.com/marbl/canu
