### ISSUE TITLE
without SGE

### ISSUE THREAD

**Issue by macmanes** [jgurtowski/nanocorr#3]
James - any plans to make nanocorr usable on a workstation (without a job scheduler), like you can for ECTOOLS? I'd like to use nanocorr on my workstation.

**Comment by jgurtowski** [comment]
I am looking into making a wrapper script that uses GNU parallel.

**Comment by macmanes** [comment]
do you accept payment in beer? No really, I imagine this would be very helpful for a lot of groups.

**Comment by macmanes** [comment]
any update on this?

**Comment by jgurtowski** [comment]
I updated the README to explain how to use GNU parallel to run on a single machine
