### ISSUE TITLE
Use -b y in qsub script

### ISSUE THREAD

**Issue by rmharrison** [jgurtowski/nanocorr#5]
For machines that default to `qsub -b n ...`, the qsub command in your README.md will throw an error trying to interpret the python nanocorr.py as a SGE script.

For example...

> Warning: no access to tty (Bad file descriptor). # Fine
> Thus no job control in this shell.                        # Fine
> import: Command not found.                             # Interpreting python as SGE script...doh!
> import: Command not found.                             # Doh
> Badly placed ()'s.                                                # More doh

Would you explicitly set -b y in your README.md command-line:

``` bash
qsub -cwd -v PATH,LD_LIBRARY_PATH -t 1:500 -j y -b y -o nanocorr_out /path/to/nanocorr.py query.fa reference.fa
```

**Comment by jgurtowski** [comment]
This is strange, I'm not sure that setting -b y is the correct solution because the script should be copied instead of run directly. It is unclear to me why this is happening as the shebang line should startup ptyhon. 

"-b n" is the default in my environment as well.
