### ISSUE TITLE
Error while running partition.py

### ISSUE THREAD

**Issue by kranthiv1889** [jgurtowski/nanocorr#7]
I encountered a Biopython error while running partition.py
`$python partition.py 100 500 Read_Staph.fa`

```
Traceback (most recent call last):
  File "partition.py", line 32, in <module>
    for record in input_data:
  File "/usr/local/lib/python2.7/dist-packages/jbio/fasta.py", line 17, in record_iterator
    if not first or not first.startswith(">"):
AttributeError: 'FastaRecord' object has no attribute 'startswith'
```

The name of my reads looks like this
`>7cf911c4-af36-4d20-b484-ceb3f4cee3c2_Basecall_2D_000_2d ReadLab_PC_Staph_PCR_0314_1_ch101_file41_strand_twodirections pass/ReadLab_PC_Staph_PCR_0314_1_ch101_file41_strand.fast5`

Can you help me with where the error is occurring?

**Comment by jgurtowski** [comment]
Ok, this issue has been fixed.
