### ISSUE TITLE
problem with pbdagcon installation step

### ISSUE THREAD

**Issue by rwinegar** [jgurtowski/nanocorr#9]
Hi James
Was quite exited to see your publication on nanocorr and anxious to try it out.  The installation instructions are very clear and have gone smoothly except for the pbgacon installation
git+https://github.com/PacificBiosciences/pbdagcon@2b14fa9c4dc1df7cc8a982f5872746dd986eeac9

The first error I get says this tree doesn't exist, so I used the latest tree.  Now I get an error about no setup.py.  I'll admit I'm  very new to Linux and Python, so there may be something basic I'm missing.  Any assistance you might provide is appreciated.

Here's the output I get at the pabdagcon step:

$ pip install git+https://github.com/PacificBiosciences/pbdagcon.git                 Collecting git+https://github.com/PacificBiosciences/pbdagcon.git
  Cloning https://github.com/PacificBiosciences/pbdagcon.git to /tmp/pip-RjoTKD-build
Initialized empty Git repository in /tmp/pip-RjoTKD-build/DALIGNER/.git/
remote: Counting objects: 279, done.
remote: Total 279 (delta 0), reused 0 (delta 0), pack-reused 279
Receiving objects: 100% (279/279), 398.56 KiB, done.
Resolving deltas: 100% (186/186), done.
Initialized empty Git repository in /tmp/pip-RjoTKD-build/DAZZ_DB/.git/
remote: Counting objects: 251, done.
remote: Total 251 (delta 0), reused 0 (delta 0), pack-reused 251
Receiving objects: 100% (251/251), 264.41 KiB, done.
Resolving deltas: 100% (175/175), done.
Initialized empty Git repository in /tmp/pip-RjoTKD-build/blasr_libcpp/.git/
remote: Counting objects: 2016, done.
remote: Total 2016 (delta 0), reused 0 (delta 0), pack-reused 2016
Receiving objects: 100% (2016/2016), 1.69 MiB | 1.44 MiB/s, done.
Resolving deltas: 100% (1281/1281), done.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 18, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-RjoTKD-build/setup.py'

**Comment by jgurtowski** [comment]
Looks like Pacbio has made changes to their pbdagcon repo. I will try to update the nanocorr code to work with their latest version but I may take some time.

**Comment by jgurtowski** [comment]
Please delete the virtual environment and rebuild it using the latest instructions.

**Comment by rwinegar** [comment]
Thanks James.  I'll try it out when I get back from vacation.  I sure appreciate the help.

**Comment by sunnvor** [comment]
Hi,
I tried to install nanocorr using the newest install instruction but I get the same error as described above. Could this be because Pacbio has made changes again?

**Comment by jgurtowski** [comment]
Make sure you are starting with a fresh virtual environment. I have
pbdagcon mirrored to my github repository so nothing should have changed.
The latest install instructions point to my version of pbdagcon.

**Comment by sunnvor** [comment]
Thanks for the reply.

I am sorry I am new to Unix and have never used virtual environment before. But I tried to start from scratch again but now I get a different error. When I install pbdagcon_python I get the output below. Do you have any suggestions what the problem might be?

> Downloading/unpacking git+https://github.com/jgurtowski/pbdagcon_python
>   Cloning https://github.com/jgurtowski/pbdagcon_python to /tmp/pip-zuUPWK-build
>   Running setup.py egg_info for package from git+https://github.com/jgurtowski/pbdagcon_python
>     zip_safe flag not set; analyzing archive contents...
> 
> ```
> Installed /tmp/pip-zuUPWK-build/.eggs/setuptools_cython-0.2.1-py2.7.egg
> 
> ./src/pbtools/pbdagcon/c_utils.pyx: cannot find cimported module 'c_aligngraph'
> Compiling ./src/pbtools/pbdagcon/c_aligngraph.pyx because it changed.
> Compiling ./src/pbtools/pbdagcon/c_utils.pyx because it changed.
> [1/2] Cythonizing ./src/pbtools/pbdagcon/c_aligngraph.pyx
> [2/2] Cythonizing ./src/pbtools/pbdagcon/c_utils.pyx
> ```
> 
> Requirement already satisfied (use --upgrade to upgrade): pbcore>=0.6.3 in ./nanocorr_ve/lib/python2.7/site-packages (from pbtools.pbdagcon==0.2.3)
> Requirement already satisfied (use --upgrade to upgrade): h5py>=2.0.1 in ./nanocorr_ve/lib/python2.7/site-packages (from pbcore>=0.6.3->pbtools.pbdagcon==0.2.3)
> Requirement already satisfied (use --upgrade to upgrade): numpy>=1.6.0 in ./nanocorr_ve/lib/python2.7/site-packages (from pbcore>=0.6.3->pbtools.pbdagcon==0.2.3)
> Requirement already satisfied (use --upgrade to upgrade): six in ./nanocorr_ve/lib/python2.7/site-packages (from h5py>=2.0.1->pbcore>=0.6.3->pbtools.pbdagcon==0.2.3)
> Installing collected packages: pbtools.pbdagcon
>   Running setup.py install for pbtools.pbdagcon
>     ./src/pbtools/pbdagcon/c_utils.pyx: cannot find cimported module 'c_aligngraph'
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-zuUPWK-build/setup.py", line 29, in <module>
>         "pbcore >= 0.6.3"
>       File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
>         dist.run_commands()
>       File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
>         self.run_command(cmd)
>       File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "/software/nanocorr/nanocorr_ve/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
>         return orig.install.run(self)
>       File "/usr/lib64/python2.7/distutils/command/install.py", line 563, in run
>         self.run_command('build')
>       File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
>         self.distribution.run_command(command)
>       File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
>         self.run_command(cmd_name)
>       File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
>         self.distribution.run_command(command)
>       File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
>         cmd_obj.run()
>       File "/software/nanocorr/nanocorr_ve/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 77, in run
>         _build_ext.run(self)
>       File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 339, in run
>         self.build_extensions()
>       File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
>         self.build_extension(ext)
>       File "/software/nanocorr/nanocorr_ve/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 193, in build_extension
>         ext._convert_pyx_sources_to_lang()
>     AttributeError: Extension instance has no attribute '_convert_pyx_sources_to_lang'
>     Complete output from command /software/nanocorr/nanocorr_ve/bin/python -c "import setuptools;__file__='/tmp/pip-zuUPWK-build/setup.py';exec(compile(open(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-yjWia_-record/install-record.txt --single-version-externally-managed --install-headers /software/nanocorr/nanocorr_ve/include/site/python2.7:
>     running install
> 
> running build
> 
> running build_py
> 
> creating build
> 
> creating build/lib.linux-x86_64-2.7
> 
> creating build/lib.linux-x86_64-2.7/pbtools
> 
> copying src/pbtools/**init**.py -> build/lib.linux-x86_64-2.7/pbtools
> 
> creating build/lib.linux-x86_64-2.7/pbtools/pbdagcon
> 
> copying src/pbtools/pbdagcon/**init**.py -> build/lib.linux-x86_64-2.7/pbtools/pbdagcon
> 
> copying src/pbtools/pbdagcon/aligngraph.py -> build/lib.linux-x86_64-2.7/pbtools/pbdagcon
> 
> copying src/pbtools/pbdagcon/vis_utils.py -> build/lib.linux-x86_64-2.7/pbtools/pbdagcon
> 
> copying src/pbtools/pbdagcon/utils.py -> build/lib.linux-x86_64-2.7/pbtools/pbdagcon
> 
> copying src/pbtools/pbdagcon/q_sense.py -> build/lib.linux-x86_64-2.7/pbtools/pbdagcon
> 
> running build_ext
> 
> ./src/pbtools/pbdagcon/c_utils.pyx: cannot find cimported module 'c_aligngraph'
> 
> Traceback (most recent call last):
> 
>   File "<string>", line 1, in <module>
> 
>   File "/tmp/pip-zuUPWK-build/setup.py", line 29, in <module>
> 
> ```
> "pbcore >= 0.6.3"
> ```
> 
>   File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
> 
> ```
> dist.run_commands()
> ```
> 
>   File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
> 
> ```
> self.run_command(cmd)
> ```
> 
>   File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
> 
> ```
> cmd_obj.run()
> ```
> 
>   File "/software/nanocorr/nanocorr_ve/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
> 
> ```
> return orig.install.run(self)
> ```
> 
>   File "/usr/lib64/python2.7/distutils/command/install.py", line 563, in run
> 
> ```
> self.run_command('build')
> ```
> 
>   File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
> 
> ```
> self.distribution.run_command(command)
> ```
> 
>   File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
> 
> ```
> cmd_obj.run()
> ```
> 
>   File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
> 
> ```
> self.run_command(cmd_name)
> ```
> 
>   File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
> 
> ```
> self.distribution.run_command(command)
> ```
> 
>   File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
> 
> ```
> cmd_obj.run()
> ```
> 
>   File "/software/nanocorr/nanocorr_ve/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 77, in run
> 
> ```
> _build_ext.run(self)
> ```
> 
>   File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 339, in run
> 
> ```
> self.build_extensions()
> ```
> 
>   File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
> 
> ```
> self.build_extension(ext)
> ```
> 
>   File "/software/nanocorr/nanocorr_ve/lib/python2.7/site-packages/setuptools/command/build_ext.py", line 193, in build_extension
> 
> ```
> ext._convert_pyx_sources_to_lang()
> ```
> 
> AttributeError: Extension instance has no attribute '_convert_pyx_sources_to_lang'
> 
> ---
> 
> Cleaning up...

**Comment by jgurtowski** [comment]
You deleted the virtual env folder that is created? Or started with a new
name?

**Comment by sunnvor** [comment]
I deleted the folder, tried to source it to make sure it was gone then created a new one with the same name.
